function nll = fun_nll2d(phi_flat)
    phi = reshape(phi_flat,6,3);
    cov_mat = wishart_get_cov(phi, distances, durations);
    % covX = squeeze(cov_mat(1,1,:));
    % covY = squeeze(cov_mat(2,2,:));
    % covXY = squeeze(cov_mat(1,2,:));

% result = (0.5*sum( ...
%         log(covX .* covY .* (1 - covXY) ) + ... % here this should be the
%         correct on to use
%         (gain_error.^2) ./ covX ...
%         - 2*sqrt(covXY) .* (gain_error.*dir_error) ./ (sqrt(covX).*sqrt(covX)) + ...
%         (dir_error.^2) ./ covY + ...
%         2*log(2*pi) ));

% nll = (0.5*sum( ...
%     log(covX .* covY ) + ...
%     (gain_error.^2) ./ covX ...
%     - 2*sqrt(covXY) .* (gain_error.*dir_error) ./ (sqrt(covX).*sqrt(covX)) + ...
%     (dir_error.^2) ./ covY + ...
%     2*log(2*pi) ));

nll = -sum(log(mvnpdf([gain_error,dir_error],zeros(1,2),cov_mat)));
end
